package gmms.dao;

import gmms.domain.db.VmVehicle;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

public interface VmVehicleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Vm_Vehicle
     *
     * @mbggenerated
     */
    @Delete({
        "delete from Vm_Vehicle",
        "where VehicleNo = #{vehicleno,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(String vehicleno);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Vm_Vehicle
     *
     * @mbggenerated
     */
    @Insert({
        "insert into Vm_Vehicle (VehicleNo, PlateNo, ",
        "PlateColor, VKindNo, ",
        "Spec, VRegDate, ",
        "CustName, HandleName, ",
        "IDCard, IncName, ",
        "Fax, Phone, Address, ",
        "Zip, Email, UpdateMode, ",
        "UpdateTime, PictureDirectory, ",
        "ImageDirectory, AMemo, ",
        "BornSource, NewCarRegistNode, ",
        "userId, userNo, ",
        "userName, tid, epc, ",
        "tippwd, TagNo, OutTagNo, ",
        "TagType, InstallDate)",
        "values (#{vehicleno,jdbcType=VARCHAR}, #{plateno,jdbcType=VARCHAR}, ",
        "#{platecolor,jdbcType=VARCHAR}, #{vkindno,jdbcType=TINYINT}, ",
        "#{spec,jdbcType=DECIMAL}, #{vregdate,jdbcType=TIMESTAMP}, ",
        "#{custname,jdbcType=VARCHAR}, #{handlename,jdbcType=VARCHAR}, ",
        "#{idcard,jdbcType=VARCHAR}, #{incname,jdbcType=VARCHAR}, ",
        "#{fax,jdbcType=VARCHAR}, #{phone,jdbcType=VARCHAR}, #{address,jdbcType=VARCHAR}, ",
        "#{zip,jdbcType=VARCHAR}, #{email,jdbcType=VARCHAR}, #{updatemode,jdbcType=TINYINT}, ",
        "#{updatetime,jdbcType=TIMESTAMP}, #{picturedirectory,jdbcType=VARCHAR}, ",
        "#{imagedirectory,jdbcType=VARCHAR}, #{amemo,jdbcType=VARCHAR}, ",
        "#{bornsource,jdbcType=TINYINT}, #{newcarregistnode,jdbcType=TINYINT}, ",
        "#{userid,jdbcType=INTEGER}, #{userno,jdbcType=VARCHAR}, ",
        "#{username,jdbcType=VARCHAR}, #{tid,jdbcType=VARCHAR}, #{epc,jdbcType=VARCHAR}, ",
        "#{tippwd,jdbcType=VARCHAR}, #{tagno,jdbcType=VARCHAR}, #{outtagno,jdbcType=VARCHAR}, ",
        "#{tagtype,jdbcType=TINYINT}, #{installdate,jdbcType=TIMESTAMP})"
    })
    int insert(VmVehicle record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Vm_Vehicle
     *
     * @mbggenerated
     */
    int insertSelective(VmVehicle record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Vm_Vehicle
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "VehicleNo, PlateNo, PlateColor, VKindNo, Spec, VRegDate, CustName, HandleName, ",
        "IDCard, IncName, Fax, Phone, Address, Zip, Email, UpdateMode, UpdateTime, PictureDirectory, ",
        "ImageDirectory, AMemo, BornSource, NewCarRegistNode, userId, userNo, userName, ",
        "tid, epc, tippwd, TagNo, OutTagNo, TagType, InstallDate",
        "from Vm_Vehicle",
        "where VehicleNo = #{vehicleno,jdbcType=VARCHAR}"
    })
    @ResultMap("BaseResultMap")
    VmVehicle selectByPrimaryKey(String vehicleno);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Vm_Vehicle
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(VmVehicle record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Vm_Vehicle
     *
     * @mbggenerated
     */
    @Update({
        "update Vm_Vehicle",
        "set PlateNo = #{plateno,jdbcType=VARCHAR},",
          "PlateColor = #{platecolor,jdbcType=VARCHAR},",
          "VKindNo = #{vkindno,jdbcType=TINYINT},",
          "Spec = #{spec,jdbcType=DECIMAL},",
          "VRegDate = #{vregdate,jdbcType=TIMESTAMP},",
          "CustName = #{custname,jdbcType=VARCHAR},",
          "HandleName = #{handlename,jdbcType=VARCHAR},",
          "IDCard = #{idcard,jdbcType=VARCHAR},",
          "IncName = #{incname,jdbcType=VARCHAR},",
          "Fax = #{fax,jdbcType=VARCHAR},",
          "Phone = #{phone,jdbcType=VARCHAR},",
          "Address = #{address,jdbcType=VARCHAR},",
          "Zip = #{zip,jdbcType=VARCHAR},",
          "Email = #{email,jdbcType=VARCHAR},",
          "UpdateMode = #{updatemode,jdbcType=TINYINT},",
          "UpdateTime = #{updatetime,jdbcType=TIMESTAMP},",
          "PictureDirectory = #{picturedirectory,jdbcType=VARCHAR},",
          "ImageDirectory = #{imagedirectory,jdbcType=VARCHAR},",
          "AMemo = #{amemo,jdbcType=VARCHAR},",
          "BornSource = #{bornsource,jdbcType=TINYINT},",
          "NewCarRegistNode = #{newcarregistnode,jdbcType=TINYINT},",
          "userId = #{userid,jdbcType=INTEGER},",
          "userNo = #{userno,jdbcType=VARCHAR},",
          "userName = #{username,jdbcType=VARCHAR},",
          "tid = #{tid,jdbcType=VARCHAR},",
          "epc = #{epc,jdbcType=VARCHAR},",
          "tippwd = #{tippwd,jdbcType=VARCHAR},",
          "TagNo = #{tagno,jdbcType=VARCHAR},",
          "OutTagNo = #{outtagno,jdbcType=VARCHAR},",
          "TagType = #{tagtype,jdbcType=TINYINT},",
          "InstallDate = #{installdate,jdbcType=TIMESTAMP}",
        "where VehicleNo = #{vehicleno,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKey(VmVehicle record);
}