package gmms.domain.db;

import java.util.Date;

public class VmVehicle {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Vm_Vehicle.VehicleNo
     *
     * @mbggenerated
     */
    private String vehicleno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Vm_Vehicle.PlateNo
     *
     * @mbggenerated
     */
    private String plateno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Vm_Vehicle.PlateColor
     *
     * @mbggenerated
     */
    private String platecolor;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Vm_Vehicle.VKindNo
     *
     * @mbggenerated
     */
    private Byte vkindno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Vm_Vehicle.Spec
     *
     * @mbggenerated
     */
    private Long spec;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Vm_Vehicle.VRegDate
     *
     * @mbggenerated
     */
    private Date vregdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Vm_Vehicle.CustName
     *
     * @mbggenerated
     */
    private String custname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Vm_Vehicle.HandleName
     *
     * @mbggenerated
     */
    private String handlename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Vm_Vehicle.IDCard
     *
     * @mbggenerated
     */
    private String idcard;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Vm_Vehicle.IncName
     *
     * @mbggenerated
     */
    private String incname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Vm_Vehicle.Fax
     *
     * @mbggenerated
     */
    private String fax;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Vm_Vehicle.Phone
     *
     * @mbggenerated
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Vm_Vehicle.Address
     *
     * @mbggenerated
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Vm_Vehicle.Zip
     *
     * @mbggenerated
     */
    private String zip;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Vm_Vehicle.Email
     *
     * @mbggenerated
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Vm_Vehicle.UpdateMode
     *
     * @mbggenerated
     */
    private Byte updatemode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Vm_Vehicle.UpdateTime
     *
     * @mbggenerated
     */
    private Date updatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Vm_Vehicle.PictureDirectory
     *
     * @mbggenerated
     */
    private String picturedirectory;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Vm_Vehicle.ImageDirectory
     *
     * @mbggenerated
     */
    private String imagedirectory;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Vm_Vehicle.AMemo
     *
     * @mbggenerated
     */
    private String amemo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Vm_Vehicle.BornSource
     *
     * @mbggenerated
     */
    private Byte bornsource;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Vm_Vehicle.NewCarRegistNode
     *
     * @mbggenerated
     */
    private Byte newcarregistnode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Vm_Vehicle.userId
     *
     * @mbggenerated
     */
    private Integer userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Vm_Vehicle.userNo
     *
     * @mbggenerated
     */
    private String userno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Vm_Vehicle.userName
     *
     * @mbggenerated
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Vm_Vehicle.tid
     *
     * @mbggenerated
     */
    private String tid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Vm_Vehicle.epc
     *
     * @mbggenerated
     */
    private String epc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Vm_Vehicle.tippwd
     *
     * @mbggenerated
     */
    private String tippwd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Vm_Vehicle.TagNo
     *
     * @mbggenerated
     */
    private String tagno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Vm_Vehicle.OutTagNo
     *
     * @mbggenerated
     */
    private String outtagno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Vm_Vehicle.TagType
     *
     * @mbggenerated
     */
    private Byte tagtype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Vm_Vehicle.InstallDate
     *
     * @mbggenerated
     */
    private Date installdate;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Vm_Vehicle
     *
     * @mbggenerated
     */
    public VmVehicle(String vehicleno, String plateno, String platecolor, Byte vkindno, Long spec, Date vregdate, String custname, String handlename, String idcard, String incname, String fax, String phone, String address, String zip, String email, Byte updatemode, Date updatetime, String picturedirectory, String imagedirectory, String amemo, Byte bornsource, Byte newcarregistnode, Integer userid, String userno, String username, String tid, String epc, String tippwd, String tagno, String outtagno, Byte tagtype, Date installdate) {
        this.vehicleno = vehicleno;
        this.plateno = plateno;
        this.platecolor = platecolor;
        this.vkindno = vkindno;
        this.spec = spec;
        this.vregdate = vregdate;
        this.custname = custname;
        this.handlename = handlename;
        this.idcard = idcard;
        this.incname = incname;
        this.fax = fax;
        this.phone = phone;
        this.address = address;
        this.zip = zip;
        this.email = email;
        this.updatemode = updatemode;
        this.updatetime = updatetime;
        this.picturedirectory = picturedirectory;
        this.imagedirectory = imagedirectory;
        this.amemo = amemo;
        this.bornsource = bornsource;
        this.newcarregistnode = newcarregistnode;
        this.userid = userid;
        this.userno = userno;
        this.username = username;
        this.tid = tid;
        this.epc = epc;
        this.tippwd = tippwd;
        this.tagno = tagno;
        this.outtagno = outtagno;
        this.tagtype = tagtype;
        this.installdate = installdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Vm_Vehicle
     *
     * @mbggenerated
     */
    public VmVehicle() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Vm_Vehicle.VehicleNo
     *
     * @return the value of Vm_Vehicle.VehicleNo
     *
     * @mbggenerated
     */
    public String getVehicleno() {
        return vehicleno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Vm_Vehicle.VehicleNo
     *
     * @param vehicleno the value for Vm_Vehicle.VehicleNo
     *
     * @mbggenerated
     */
    public void setVehicleno(String vehicleno) {
        this.vehicleno = vehicleno == null ? null : vehicleno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Vm_Vehicle.PlateNo
     *
     * @return the value of Vm_Vehicle.PlateNo
     *
     * @mbggenerated
     */
    public String getPlateno() {
        return plateno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Vm_Vehicle.PlateNo
     *
     * @param plateno the value for Vm_Vehicle.PlateNo
     *
     * @mbggenerated
     */
    public void setPlateno(String plateno) {
        this.plateno = plateno == null ? null : plateno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Vm_Vehicle.PlateColor
     *
     * @return the value of Vm_Vehicle.PlateColor
     *
     * @mbggenerated
     */
    public String getPlatecolor() {
        return platecolor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Vm_Vehicle.PlateColor
     *
     * @param platecolor the value for Vm_Vehicle.PlateColor
     *
     * @mbggenerated
     */
    public void setPlatecolor(String platecolor) {
        this.platecolor = platecolor == null ? null : platecolor.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Vm_Vehicle.VKindNo
     *
     * @return the value of Vm_Vehicle.VKindNo
     *
     * @mbggenerated
     */
    public Byte getVkindno() {
        return vkindno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Vm_Vehicle.VKindNo
     *
     * @param vkindno the value for Vm_Vehicle.VKindNo
     *
     * @mbggenerated
     */
    public void setVkindno(Byte vkindno) {
        this.vkindno = vkindno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Vm_Vehicle.Spec
     *
     * @return the value of Vm_Vehicle.Spec
     *
     * @mbggenerated
     */
    public Long getSpec() {
        return spec;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Vm_Vehicle.Spec
     *
     * @param spec the value for Vm_Vehicle.Spec
     *
     * @mbggenerated
     */
    public void setSpec(Long spec) {
        this.spec = spec;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Vm_Vehicle.VRegDate
     *
     * @return the value of Vm_Vehicle.VRegDate
     *
     * @mbggenerated
     */
    public Date getVregdate() {
        return vregdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Vm_Vehicle.VRegDate
     *
     * @param vregdate the value for Vm_Vehicle.VRegDate
     *
     * @mbggenerated
     */
    public void setVregdate(Date vregdate) {
        this.vregdate = vregdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Vm_Vehicle.CustName
     *
     * @return the value of Vm_Vehicle.CustName
     *
     * @mbggenerated
     */
    public String getCustname() {
        return custname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Vm_Vehicle.CustName
     *
     * @param custname the value for Vm_Vehicle.CustName
     *
     * @mbggenerated
     */
    public void setCustname(String custname) {
        this.custname = custname == null ? null : custname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Vm_Vehicle.HandleName
     *
     * @return the value of Vm_Vehicle.HandleName
     *
     * @mbggenerated
     */
    public String getHandlename() {
        return handlename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Vm_Vehicle.HandleName
     *
     * @param handlename the value for Vm_Vehicle.HandleName
     *
     * @mbggenerated
     */
    public void setHandlename(String handlename) {
        this.handlename = handlename == null ? null : handlename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Vm_Vehicle.IDCard
     *
     * @return the value of Vm_Vehicle.IDCard
     *
     * @mbggenerated
     */
    public String getIdcard() {
        return idcard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Vm_Vehicle.IDCard
     *
     * @param idcard the value for Vm_Vehicle.IDCard
     *
     * @mbggenerated
     */
    public void setIdcard(String idcard) {
        this.idcard = idcard == null ? null : idcard.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Vm_Vehicle.IncName
     *
     * @return the value of Vm_Vehicle.IncName
     *
     * @mbggenerated
     */
    public String getIncname() {
        return incname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Vm_Vehicle.IncName
     *
     * @param incname the value for Vm_Vehicle.IncName
     *
     * @mbggenerated
     */
    public void setIncname(String incname) {
        this.incname = incname == null ? null : incname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Vm_Vehicle.Fax
     *
     * @return the value of Vm_Vehicle.Fax
     *
     * @mbggenerated
     */
    public String getFax() {
        return fax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Vm_Vehicle.Fax
     *
     * @param fax the value for Vm_Vehicle.Fax
     *
     * @mbggenerated
     */
    public void setFax(String fax) {
        this.fax = fax == null ? null : fax.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Vm_Vehicle.Phone
     *
     * @return the value of Vm_Vehicle.Phone
     *
     * @mbggenerated
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Vm_Vehicle.Phone
     *
     * @param phone the value for Vm_Vehicle.Phone
     *
     * @mbggenerated
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Vm_Vehicle.Address
     *
     * @return the value of Vm_Vehicle.Address
     *
     * @mbggenerated
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Vm_Vehicle.Address
     *
     * @param address the value for Vm_Vehicle.Address
     *
     * @mbggenerated
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Vm_Vehicle.Zip
     *
     * @return the value of Vm_Vehicle.Zip
     *
     * @mbggenerated
     */
    public String getZip() {
        return zip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Vm_Vehicle.Zip
     *
     * @param zip the value for Vm_Vehicle.Zip
     *
     * @mbggenerated
     */
    public void setZip(String zip) {
        this.zip = zip == null ? null : zip.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Vm_Vehicle.Email
     *
     * @return the value of Vm_Vehicle.Email
     *
     * @mbggenerated
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Vm_Vehicle.Email
     *
     * @param email the value for Vm_Vehicle.Email
     *
     * @mbggenerated
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Vm_Vehicle.UpdateMode
     *
     * @return the value of Vm_Vehicle.UpdateMode
     *
     * @mbggenerated
     */
    public Byte getUpdatemode() {
        return updatemode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Vm_Vehicle.UpdateMode
     *
     * @param updatemode the value for Vm_Vehicle.UpdateMode
     *
     * @mbggenerated
     */
    public void setUpdatemode(Byte updatemode) {
        this.updatemode = updatemode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Vm_Vehicle.UpdateTime
     *
     * @return the value of Vm_Vehicle.UpdateTime
     *
     * @mbggenerated
     */
    public Date getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Vm_Vehicle.UpdateTime
     *
     * @param updatetime the value for Vm_Vehicle.UpdateTime
     *
     * @mbggenerated
     */
    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Vm_Vehicle.PictureDirectory
     *
     * @return the value of Vm_Vehicle.PictureDirectory
     *
     * @mbggenerated
     */
    public String getPicturedirectory() {
        return picturedirectory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Vm_Vehicle.PictureDirectory
     *
     * @param picturedirectory the value for Vm_Vehicle.PictureDirectory
     *
     * @mbggenerated
     */
    public void setPicturedirectory(String picturedirectory) {
        this.picturedirectory = picturedirectory == null ? null : picturedirectory.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Vm_Vehicle.ImageDirectory
     *
     * @return the value of Vm_Vehicle.ImageDirectory
     *
     * @mbggenerated
     */
    public String getImagedirectory() {
        return imagedirectory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Vm_Vehicle.ImageDirectory
     *
     * @param imagedirectory the value for Vm_Vehicle.ImageDirectory
     *
     * @mbggenerated
     */
    public void setImagedirectory(String imagedirectory) {
        this.imagedirectory = imagedirectory == null ? null : imagedirectory.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Vm_Vehicle.AMemo
     *
     * @return the value of Vm_Vehicle.AMemo
     *
     * @mbggenerated
     */
    public String getAmemo() {
        return amemo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Vm_Vehicle.AMemo
     *
     * @param amemo the value for Vm_Vehicle.AMemo
     *
     * @mbggenerated
     */
    public void setAmemo(String amemo) {
        this.amemo = amemo == null ? null : amemo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Vm_Vehicle.BornSource
     *
     * @return the value of Vm_Vehicle.BornSource
     *
     * @mbggenerated
     */
    public Byte getBornsource() {
        return bornsource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Vm_Vehicle.BornSource
     *
     * @param bornsource the value for Vm_Vehicle.BornSource
     *
     * @mbggenerated
     */
    public void setBornsource(Byte bornsource) {
        this.bornsource = bornsource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Vm_Vehicle.NewCarRegistNode
     *
     * @return the value of Vm_Vehicle.NewCarRegistNode
     *
     * @mbggenerated
     */
    public Byte getNewcarregistnode() {
        return newcarregistnode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Vm_Vehicle.NewCarRegistNode
     *
     * @param newcarregistnode the value for Vm_Vehicle.NewCarRegistNode
     *
     * @mbggenerated
     */
    public void setNewcarregistnode(Byte newcarregistnode) {
        this.newcarregistnode = newcarregistnode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Vm_Vehicle.userId
     *
     * @return the value of Vm_Vehicle.userId
     *
     * @mbggenerated
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Vm_Vehicle.userId
     *
     * @param userid the value for Vm_Vehicle.userId
     *
     * @mbggenerated
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Vm_Vehicle.userNo
     *
     * @return the value of Vm_Vehicle.userNo
     *
     * @mbggenerated
     */
    public String getUserno() {
        return userno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Vm_Vehicle.userNo
     *
     * @param userno the value for Vm_Vehicle.userNo
     *
     * @mbggenerated
     */
    public void setUserno(String userno) {
        this.userno = userno == null ? null : userno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Vm_Vehicle.userName
     *
     * @return the value of Vm_Vehicle.userName
     *
     * @mbggenerated
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Vm_Vehicle.userName
     *
     * @param username the value for Vm_Vehicle.userName
     *
     * @mbggenerated
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Vm_Vehicle.tid
     *
     * @return the value of Vm_Vehicle.tid
     *
     * @mbggenerated
     */
    public String getTid() {
        return tid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Vm_Vehicle.tid
     *
     * @param tid the value for Vm_Vehicle.tid
     *
     * @mbggenerated
     */
    public void setTid(String tid) {
        this.tid = tid == null ? null : tid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Vm_Vehicle.epc
     *
     * @return the value of Vm_Vehicle.epc
     *
     * @mbggenerated
     */
    public String getEpc() {
        return epc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Vm_Vehicle.epc
     *
     * @param epc the value for Vm_Vehicle.epc
     *
     * @mbggenerated
     */
    public void setEpc(String epc) {
        this.epc = epc == null ? null : epc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Vm_Vehicle.tippwd
     *
     * @return the value of Vm_Vehicle.tippwd
     *
     * @mbggenerated
     */
    public String getTippwd() {
        return tippwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Vm_Vehicle.tippwd
     *
     * @param tippwd the value for Vm_Vehicle.tippwd
     *
     * @mbggenerated
     */
    public void setTippwd(String tippwd) {
        this.tippwd = tippwd == null ? null : tippwd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Vm_Vehicle.TagNo
     *
     * @return the value of Vm_Vehicle.TagNo
     *
     * @mbggenerated
     */
    public String getTagno() {
        return tagno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Vm_Vehicle.TagNo
     *
     * @param tagno the value for Vm_Vehicle.TagNo
     *
     * @mbggenerated
     */
    public void setTagno(String tagno) {
        this.tagno = tagno == null ? null : tagno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Vm_Vehicle.OutTagNo
     *
     * @return the value of Vm_Vehicle.OutTagNo
     *
     * @mbggenerated
     */
    public String getOuttagno() {
        return outtagno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Vm_Vehicle.OutTagNo
     *
     * @param outtagno the value for Vm_Vehicle.OutTagNo
     *
     * @mbggenerated
     */
    public void setOuttagno(String outtagno) {
        this.outtagno = outtagno == null ? null : outtagno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Vm_Vehicle.TagType
     *
     * @return the value of Vm_Vehicle.TagType
     *
     * @mbggenerated
     */
    public Byte getTagtype() {
        return tagtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Vm_Vehicle.TagType
     *
     * @param tagtype the value for Vm_Vehicle.TagType
     *
     * @mbggenerated
     */
    public void setTagtype(Byte tagtype) {
        this.tagtype = tagtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Vm_Vehicle.InstallDate
     *
     * @return the value of Vm_Vehicle.InstallDate
     *
     * @mbggenerated
     */
    public Date getInstalldate() {
        return installdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Vm_Vehicle.InstallDate
     *
     * @param installdate the value for Vm_Vehicle.InstallDate
     *
     * @mbggenerated
     */
    public void setInstalldate(Date installdate) {
        this.installdate = installdate;
    }
}